elt_source/ELT.WEB-VS2013/ELT.WEB/Controllers/AspPrintPDFController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ELT.WEB.Models;
using ELT.BL;
using ELT.CDT;
using System.IO;

namespace ELT.WEB.Controllers
{
    [Authorize]
    public class AspPrintPDFController : Controller
    {        // GET: ~/aspPrintPDF/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult HAWBPrintPDF(AspPrintPDFAirExportHAWB model)
        {
            string url = string.Empty;
            model.HAWB = Request["HAWB"];
            url = GenerateHAWBPrintUrl(model);
            Stream receiveStream = null;
            ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
            return File(receiveStream, "application/pdf", model.HAWB + ".pdf");
       
        }
        [HttpGet]
        [Authorize]
        public ActionResult HAWBPrintPDF(string HAWB)
        {
            AspPrintPDFAirExportHAWB model = new AspPrintPDFAirExportHAWB() {HAWB = HAWB };
            return View(model);
        }
       
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult MAWBPrintPDF(AspPrintPDFAirExportMAWB model)
        {
            string url = string.Empty;        
            url = GenerateMAWBPrintUrl(model);
           Stream receiveStream = null;
           ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
           return File(receiveStream, "application/pdf", model.MAWB + ".pdf");
           // return new ContentResult() { Content = "<script>parent.ShowInModalBox('" + url + "');</script>" };        
        }
        [HttpGet]
        [Authorize]
        public ActionResult MAWBPrintPDF(string MAWB)
        {
            AspPrintPDFAirExportMAWB model = new AspPrintPDFAirExportMAWB() { ManifestTypeList = GetManifestTypesMAWB(MAWB), MAWB = MAWB };
            return View(model);
        }  
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult HBOLPrintPDF(AspPrintPDFOceanExportHBOL model)
        {
            string url = string.Empty;
          
            url = GenerateHBOLPrintUrl(model);
          
            Stream receiveStream = null;
            ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
            return File(receiveStream, "application/pdf", model.HBOL + ".pdf");
        }
        [HttpGet]
        [Authorize]
        public ActionResult HBOLPrintPDF(string HBOL)
        {
            AspPrintPDFOceanExportHBOL model = new AspPrintPDFOceanExportHBOL() { HBOL = HBOL };
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult MBOLPrintPDF(AspPrintPDFOceanExportMBOL model)
        {
            string url = string.Empty;
        
            url = GenerateMBOLPrintUrl(model);
            Stream receiveStream = null;
           ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
           return File(receiveStream, "application/pdf", model.MBOL + ".pdf");
        }
        [HttpGet]
        [Authorize]
        public ActionResult MBOLPrintPDF(string MBOL)
        {
            AspPrintPDFOceanExportMBOL model = new AspPrintPDFOceanExportMBOL() { ManifestTypeList = GetManifestTypesMAWB(MBOL), MBOL = MBOL };
            return View(model);
        }
      
  
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DmHAWBPrintPDF(AspPrintPDFAirExportDmHAWB model)
        {
            string url = string.Empty;
            model.DmHAWB = Request["DmHAWB"];
            url = GenerateDmHAWBPrintUrl(model);
            Stream receiveStream = null;
            ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
            return File(receiveStream, "application/pdf", model.DmHAWB + ".pdf");
        }
        [HttpGet]
        [Authorize]
        public ActionResult DmHAWBPrintPDF(string DmHAWB)
        {
            AspPrintPDFAirExportDmHAWB model = new AspPrintPDFAirExportDmHAWB() { DmHAWB = DmHAWB };
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DmMAWBPrintPDF(AspPrintPDFAirExportDmMAWB model)
        {
            string url = string.Empty;

            url = GenerateDmMAWBPrintUrl(model);
            Stream receiveStream = null;
            ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
            return File(receiveStream, "application/pdf", model.DmMAWB + ".pdf");
        }
        [HttpGet]
        [Authorize]
        public ActionResult DmMAWBPrintPDF(string DmMAWB)
        {
            AspPrintPDFAirExportDmMAWB model = new AspPrintPDFAirExportDmMAWB() { ManifestTypeList = GetManifestTypesDmMAWB(DmMAWB), DmMAWB = DmMAWB };
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult GroundMAWBPrintPDF(AspPrintPDFGroundMAWB model)
        {
            string url = string.Empty;

            url = GenerateGroundMAWBPrintUrl(model);
            Stream receiveStream = null;
            ELT.COMMON.Util.ReadFileStream(url, ref receiveStream);
            return File(receiveStream, "application/pdf", model.MAWB + ".pdf");
        }
        [HttpGet]
        [Authorize]
        public ActionResult GroundMAWBPrintPDF(string MAWB)
        {
            AspPrintPDFGroundMAWB model = new AspPrintPDFGroundMAWB() { MAWB = MAWB };
            return View(model);
        }


        private List<SelectListItem> GetManifestTypesMAWB(string MAWB)
        {
            AirExportBL aeBL = new AirExportBL();

            AuthenticationBL bl = new AuthenticationBL();
            ELTUser authBLGetELTUser = null;
            authBLGetELTUser = bl.GetELTUser( User.Identity.Name);
           
            int ELT_ACCOUNT_NUMBER = Convert.ToInt32(authBLGetELTUser.elt_account_number);
            List<ManifestAgentInfo> agents = aeBL.GetAgentsInMAWB(ELT_ACCOUNT_NUMBER, MAWB);
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Consolidated Manifest", Value = "All" });
            foreach (var agent in agents)
            {
                string text = agent.agent_name;
                string value = String.Format("MAWB={0}&Agent={1}&MasterAgentNo=0", MAWB, agent.agent_no);
                items.Add(new SelectListItem { Text = text, Value = HttpUtility.HtmlEncode(value) });
            }

            return items;
        }
        private List<SelectListItem> GetManifestTypesMBOL(string MBOL)
        {

            OceanExportBL oeBL = new OceanExportBL();
            AuthenticationBL bl = new AuthenticationBL();
            ELTUser authBLGetELTUser = null;
            authBLGetELTUser = bl.GetELTUser( User.Identity.Name);
           
            int ELT_ACCOUNT_NUMBER = Convert.ToInt32(authBLGetELTUser.elt_account_number);
            List<ManifestAgentInfo> agents = oeBL.GetAgentsInMBOL(ELT_ACCOUNT_NUMBER, MBOL);
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Consolidated Manifest", Value = "All" });
            foreach (var agent in agents)
            {
                string text = agent.agent_name;
                string value = String.Format("MBOL={0}&Agent={1}&MasterAgentNo=0", MBOL, agent.agent_no);
                items.Add(new SelectListItem { Text = text, Value = HttpUtility.HtmlEncode(value) });
            }

            return items;
        }
        private List<SelectListItem> GetManifestTypesDmMAWB(string DmMAWB)
        {

            DomesticFreightBL aeBL = new DomesticFreightBL();
            AuthenticationBL bl = new AuthenticationBL();
            ELTUser authBLGetELTUser = null;
            authBLGetELTUser = bl.GetELTUser( User.Identity.Name);
           
            int ELT_ACCOUNT_NUMBER = Convert.ToInt32(authBLGetELTUser.elt_account_number);
            List<ManifestAgentInfo> agents = aeBL.GetAgentsInDmMAWB(ELT_ACCOUNT_NUMBER, DmMAWB);
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Consolidated Manifest", Value = "All" });
            foreach (var agent in agents)
            {
                string text = agent.agent_name;
                string value = String.Format("mawb={0}&Agent={1}&MasterAgentNo=0", DmMAWB, agent.agent_no);
                items.Add(new SelectListItem { Text = text, Value = HttpUtility.HtmlEncode(value) });
            }

            return items;
        }
        private string GenerateMBOLPrintUrl(AspPrintPDFOceanExportMBOL model)
        {
            string url = string.Empty;
            if (model.DocType == "1")
            {
                url = String.Format("/asp/ocean_export/bol_instruction.asp?BookingNum={0}",  model.MBOL, model.PDFCopyType);
                           
            }
            else if (model.DocType == "2")
            {
                if (model.ManifestType == "All")
                {
                    url = String.Format("/asp/ocean_export/manifest_pdf.asp?MBOL={0}",  model.MBOL);
                  

                }
                else if (model.ManifestType != "All")
                {
                    url = String.Format("/asp/ocean_export/manifest_pdf.asp?{0}", model.ManifestType);
                  
                }
            }
          
            return HttpUtility.UrlEncode(url);
        }
        private string GenerateHBOLPrintUrl(AspPrintPDFOceanExportHBOL model)
        {
            string url = string.Empty;
            if (model.DocType == "1")
            {
                url = String.Format("/asp/ocean_export/hbol_pdf.asp?hbol={0}&Copy={1}",  model.HBOL, model.PDFCopyType);
                             
            }
            else if (model.DocType == "2")
            {

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/DmHAWBPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFAirExportDmHAWB
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("DmHAWBPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.DmHAWB)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
   
    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/DmMAWBPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFAirExportDmMAWB
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("DmMAWBPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.DmMAWB)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
    @Html.DropDownListFor(m => m.ManifestType, Model.ManifestTypeList, new { id = "drpManifestType", @class = "Sdropd" })
 
    @Html.DropDownListFor(m => m.IACType, Model.IACTypeList, new { id = "drpIACType", @class = "Sdropd" })    

    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }

        if (obj.value ==
        '2') {
            $('#drpManifestType').show();
            $('#chkAddInfo').show();
         }

        if (obj.value ==
        '3') { $('#drpIACType').show(); }
         
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/GroundMAWBPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFGroundMAWB
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("GroundMAWBPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.MAWB)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
  
       </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }

        if (obj.value ==
        '2') {
            $('#drpManifestType').show();
            $('#chkAddInfo').show();
         }

        if (obj.value ==
        '3') { $('#drpIACType').show(); }
         
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/HAWBPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFAirExportHAWB
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("HAWBPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.HAWB)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
   
    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/HBOLPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFOceanExportHBOL
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("HBOLPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.HBOL)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
   
    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/MAWBPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFAirExportMAWB
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("MAWBPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.MAWB)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
    @Html.DropDownListFor(m => m.PDFCopyType, Model.PDFCopyTypeList, new { id = "drpPDFCopyType", @class = "Sdropd" })
    @Html.DropDownListFor(m => m.ManifestType, Model.ManifestTypeList, new { id = "drpManifestType", @class = "Sdropd" })
   <div class="Sdropd" id ="chkAddInfo"> @Html.CheckBoxFor(m => m.IncludeAdditionalInfo) Include contact information and shipper and consignee.</div>
    @Html.DropDownListFor(m => m.IACType, Model.IACTypeList, new { id = "drpIACType", @class = "Sdropd" })    

    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>
    
}

<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '1') { $('#drpPDFCopyType').show(); }

        if (obj.value ==
        '2') {
            $('#drpManifestType').show();
            $('#chkAddInfo').show();
         }

        if (obj.value ==
        '3') { $('#drpIACType').show(); }
         
       
    }

    

</script>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/AspPrintPDF/MBOLPrintPDF.cshtml
@model ELT.WEB.Models.AspPrintPDFOceanExportMBOL
@{
    ViewBag.Title = "AEPNL";
    Layout = "~/Views/Shared/_LayoutPopUp.cshtml";
}
<style  type="text/css">
header {height:10px;}
</style>
@using (Html.BeginForm("MBOLPrintPDF", "AspPrintPDF", FormMethod.Post, new { id = "formPrint" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.MBOL)
    <div style="margin-top:20px; margin-left:20px;">
    <table>    
    <tr> 
    <td>@Html.DropDownListFor(m => m.DocType, Model.DocTypeList, new { id = "drpDocType", onchange = "ShowSelected(this);" })</td>   

    </tr>
    <tr><td> 
  
    @Html.DropDownListFor(m => m.ManifestType, Model.ManifestTypeList, new { id = "drpManifestType", @class = "Sdropd" })
   
    </td></tr>
    <tr><td><input type="submit" id ="btnPrint" value="PRINT" /></td></tr>
    </table>
    </div>    
}
<script type="text/javascript">

    $(document).ready(function () {
        HideAllSubDropDowns();
        $('#btnPrint').hide();
    });
    function HideAllSubDropDowns() {
        $(".Sdropd").hide();
    }
    function ShowSelected(obj) {
        HideAllSubDropDowns();
        if (obj.value ==
        '0') { $('#btnPrint').hide(); } else {
            $('#btnPrint').show();
        }

        if (obj.value ==
        '2') { $('#drpManifestType').show(); }       
    }
</script>