elt_source/ELT.WEB-VS2013/ELT.WEB/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ELT.COMMON;
using ELT.WEB.Models;
using ELT.CDT;
using ELT.WEB.Filters; 

namespace ELT.WEB.Controllers
{
    [Authorize]
    public partial class MasterDataController : OperationBaseController
    {
        public MasterDataController()
        {
            if (System.Web.HttpContext.Current.Session != null)
            {
                SetSubMenu(MainMenuContext.MasterData);
                SetProductMenu(CurrentMenu.Context);
            }
        }

        public ActionResult Index()
        {
            return View();
        }
        [CheckSession]
        public ActionResult ClientPartnerProfile(string param)
        {
            CheckAccess();
            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
        public ActionResult ClientPartnerProfileDetail(string param)
        {

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }

          [CheckSession]
        public ActionResult Port(string param)
        {
            CheckAccess();

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
          [CheckSession]
        public ActionResult FreightLocation(string param)
          {
              CheckAccess();

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
          [CheckSession]
        public ActionResult ScheduleB(string param)
          {
              CheckAccess();

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
        [CheckSession]
        public ActionResult ChargeItems(string param)
        {
            CheckAccess();
            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
          [CheckSession]
        public ActionResult CostItems(string param)
        {
            CheckAccess();

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
          [CheckSession]
        public ActionResult MasterAWBNo(string param)
          {
              CheckAccess();

            if (param != null)
                param = "?" + param;
            ViewBag.Params = param;
            return View();
        }
    }
}

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/ChargeItems.cshtml
@{
    ViewBag.Title = "ChargeItems";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/charge_items.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/ClientPartnerProfile.cshtml
@{
    ViewBag.Title = "ClientPartnerProfile";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" height="1800" src="@Url.Content("~/ASP/master_data/client_profile_list.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/ClientPartnerProfileDetail.cshtml
@{
    ViewBag.Title = "ClientPartnerProfileDetail";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/client_profile.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/CostItems.cshtml
@{
    ViewBag.Title = "CostItems";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/cost_items.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/CustomerSellingRateTable.cshtml
@model ELT.WEB.Models.RateTable 
 @using (Ajax.BeginForm("RateTable", "MasterData", new AjaxOptions() { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "mGridDiv" }, new { @id = "formTable" }))
 {
      @Html.HiddenFor(m => m.RateType, new { id = "h_rate_type" })
    @Html.HiddenFor(m => m.ShouldAdd)
<div class="masterGrid">
    <table>
        <thead><tr><td colspan="20"> <div class="actionHeader"><ul><li><a href="javascript:void(0)" onclick="AddRoute()"><span> Add Route</span></a></li></ul></div> </tr></thead>
        <tbody>
            @Html.EditorFor(m=>m.RateRoutes)
        </tbody>

    </table>

  
</div>
    @Html.Hidden("ActionParam", "", new { id = "ActionParam" })
    <input type="submit" value="submit" id="btnSubmit" />
 }

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/FreightLocation.cshtml
@{
    ViewBag.Title = "FreightLocation";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/edit_freight.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}
 <link href="@Url.Content("~/ASP/css/defaultpage.css")" rel="stylesheet" type="text/css" >
  <style type="text/css">
 p
 {
    text-align:left;
 }
 </style>
<div class="body">
    <div id="rightnavi">
        <h2>
            MASTER DATA
        </h2>
        <p>
            This Tab is where most of the records are created and access that will in turn be
            used throughout the rest of the system. This data includes information about your
            clients, carriers, consignees, and agents. It also includes information about your
            AE rates, Ports, and Schedule B information for AES.</p>
        <h4>
            <a href="/ASP/Code/DOMESTIC_PORT_CODE.xls" target="_blank">Domestic Port ID</a></h4>
        <h4>
            <a href="/ASP/Code/FOREIGN_PORT_CODE.xls" target="_blank">Foreign Port ID</a></h4>
        <h4 class="bottommargin">
            <a href="http://www.census.gov/foreign-trade/schedules/b/index.html" target="_blank">
                Schedule B</a></h4>
        <!-- will add functon later
	<h3 class="bold">Recent Works </h3>
	<ul class="recentworks">
	<li><a href="#">File name 1</a></li>
	<li><a href="#">File name 2</a></li>
	<li><a href="#">File name 3</a></li>
	<li><a href="#">File name 4</a></li>
	</ul>-->
        <div id="linebreak">
        </div>
        <h2>
            RESOURCES</h2>
        <h3>
            User's Handbook</h3>
        <p>
            A first time user or want to learn how to use FreightEasy? <a href="/images/freighteasy/images/FreightEasy-Guide.pdf"
                target="_blank">Download</a> a User's Handbook.
            <h3>
                Support Center
            </h3>
            <p>
                We are ready to help you. For technical support, email to <a href="mailto:support@e-logitech.net?subject=Support for FreightEasy-Master Data">
                    support@e-logitech.net</a> or call us at 1-877-680-EASY(3279).</p>
    </div>
    <div id="leftfloat">
        <div id="announcement">
            <p>
                <span class="bold style10"><span class="style12">The Beta </span><a onclick="javascript:if(window.parent.historyStorage) {window.parent.historyStorage.reset()};parent.location.href='/MasterData/ClientPartnerProfile/PostBack=false';return false;"
                    href="javascript:">Client/Partner Profile </a><span class="style12">is now released.</span></span>
                <br>
                Thank you for your interest in Beta Client/Partner Profile. After we reviewed bugs
                and suggestions, we have implemented it to improve the overall user experience.</p>
        </div>
        <div id="md">
            <p>
                <span class="bold"><a onclick="javascript:if(window.parent.historyStorage) {window.parent.historyStorage.reset()};parent.location.href='/MasterData/ClientPartnerProfile/PostBack=false';return false;"
                    href="javascript:">Client/Partner Profile</a></span> - This area is where all
                contact and business information is kept for all the companies you do business with.
                This information will be used throughout the system, depending on what business
                type you assign to each record.</p>
        </div>
        <div id="md2">
            <p>
                <span class="bold"><a href="/MasterData/RateManager">Rate Manager</a></span>
                - This area is where you input your rate tables for Air Export. Air Import, IATA,
                Airline Buying, Customer Selling and Agent Buying rates can all be inputted. These
                rates will be automatically populated while making a shipment in the appropriate
                circumstances.</p>
        </div>
        <div id="md3">
            <p>
                <span class="bold"><a href="/MasterData/Port" target="_parent">Port,</a></span>
                <span class="bold"><a href="/MasterData/FreightLocation" target="_parent">Freight
                    Location,</a></span> 
                <span class="bold"><a href="/MasterData/ScheduleB"
                        target="_parent">Schedule B</a></span> - This area is where you configure
                which of these types of information will show up in your system. This helps keep
                menus throughout the system at a manageable size, and makes sure only the items
                you need will be in those menus.</p>
        </div>
        <div id="mdbottom">
            <p>
                <span class="bold"><a href="/MasterData/MasterAWBNo" target="_parent">MAWB No.</a></span>
                - This area is where you enter new blocks of MAWB numbers for your air carriers.
                You can also close out MAWB’s that are old so they remain in the system, but do
                not clutter up your menus.</p>
        </div>
    </div>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/MasterAWBNo.cshtml
@{
    ViewBag.Title = "MasterAWBNo";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/booking_number.asp" + ViewBag.Params)"></iframe>

<h2>MasterAWBNo</h2>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/Port.cshtml
@{
    ViewBag.Title = "Port";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}

<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/ASP/master_data/edit_port.asp" + ViewBag.Params)"></iframe>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/RateManager.cshtml
@using System.Configuration
@{
    ViewBag.Title = "RateManager";
    Layout = "~/Views/Shared/_LayoutMasterData.cshtml";
}

@*<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css" />*@
<link rel="stylesheet" href="~/Content/font-awesome-4.6.3/css/font-awesome.min.css" />

<!--[if IE 7]>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome-ie7.min.css" />
<![endif]-->

<link href="~/app/modules/js-custom-select-master/css/style.css" rel="stylesheet" />

<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/angular-cookies.min.js" type="text/javascript"></script>
<script src="~/Scripts/angular-cookies.min.js" type="text/javascript"></script>
<script src="~/Scripts/angular-cookies.min.js" type="text/javascript"></script>
<script src="~/Scripts/angular-animate.min.js"></script>
<script src="~/Scripts/angular-route.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/app/modules/js-custom-select-master/js/customSelect.js"></script>
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/app/modules/rateManager/appStyle.css" rel="stylesheet" />
<script src="~/app/modules/rateManager/services/rateManagerService.js"></script>
<script src="~/app/modules/rateManager/services/referenceService.js"></script>
<script src="~/app/modules/rateManager/services/accountService.js"></script>
<script src="~/app/modules/rateManager/controllers/rateManagerController.js"></script>
<script src="~/app/modules/rateManager/app.js"></script>
<script src="~/app/modules/rateManager/directives/customerSellingGrid.js"></script>
<script src="~/app/modules/rateManager/directives/agentBuyingGrid.js"></script>
<script src="~/app/modules/rateManager/directives/iataRateGrid.js"></script>
<script src="~/app/modules/rateManager/directives/airlineBuyingGrid.js"></script>
<script src="~/app/modules/rateManager/directives/pager.js"></script>


<input id="apiBaseUrl" type="hidden" value="@ConfigurationManager.AppSettings["ApiBaseUrl"]" />
<input id="rootUrl" type="hidden" value="@ConfigurationManager.AppSettings["RootUrl"]" />
<input id="pageSize" type="hidden" value="@ConfigurationManager.AppSettings["RatePageSize"]"/>
<input id="oldModel" type="hidden"/>

<div ng-app="appRateManager" ng-controller="RateManagerController" class="parent">


   
        <div class="modal fade " id="displayMsg" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" >Current Status</h4>
                    </div>
                    <div class="modal-body ">
                        <p>
                            {{message}}
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                       
                    </div>
                </div>
            </div>
        </div>
    <div class="modal fade " id="displayError" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" >Error</h4>
                </div>
                <div class="modal-body ">
                    <p>
                        {{error}}
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>
   
    <form id="form-rate-man">
        <div class="panel panel-default filterBox">
            <!-- Default panel contents -->
            <!-- Table -->
            <table class="table">
                <tr>
                    <td>
                        <div class="panel-heading">RATE MANAGER</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-inline">
                            <div style="display: inline-table; margin-right: 10px;">
                                <label>Rate Type </label>
                            </div>
                            <div style="display: inline-table; margin-right: 100px">
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        {{rateTypeText}}
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li ng-click="rateTypeChanged(4)"><a href="#">Customer Selling Rate</a></li>
                                        <li ng-click="rateTypeChanged(3)"><a href="#">Airline Buying Rate </a></li>
                                        <li ng-click="rateTypeChanged(1)"><a href="#">Agent Buying Rate</a></li>
                                        <li ng-click="rateTypeChanged(5)"><a href="#">IATA Rate</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div style="display: inline-table" ng-show="rateTypeId==4">
                                <label>Customer Name </label>(Optional)
                            </div>
                            <div style="display: inline-table" ng-show="rateTypeId==4">
                                <div custom-select="a.text for a in searchAsync($searchTerm)" custom-select-options="{ 'async': true }" ng-model="customer"></div>
                            </div>

                            <div style="display: inline-table" ng-show="rateTypeId==1">
                                <label>Agent Name </label>(Optional)
                            </div>
                            <div style="display: inline-table" ng-show="rateTypeId==1">
                                <div custom-select="a.text for a in searchAsyncAgent($searchTerm)" custom-select-options="{ 'async': true }" ng-model="agent"></div>
                            </div>
                            <div class="form-group" ng-init="page_load('L')">
                                <button type="button" ng-click="getRates()" class="btn btn-default">Go</button>
                            </div>

                        </div>
                    </td>
                </tr>
            </table>
            <table class="table">

                <tr>
                    <td>
                        <div>
                            <customer-selling-rate-grid ng-model="model.companyWrappers" rate-type="4" on-change="updateModel(model)" ng-show="rateTypeId==4">

                                <div class="form-group" style="text-align: center">
                                    <button class="button btn-primary" ng-click="saveTable()"><span class="glyphicon glyphicon-floppy-save"></span> Save Table</button>
                                </div>
                            </customer-selling-rate-grid>
                            <iata-rate-grid ng-model="model.iataRateTable" on-change="updateModel(model)" rate-type="5" ng-show="rateTypeId==5">
                                <div class="form-group" style="text-align: center">
                                    <button class="button btn-primary" ng-click="saveTable()"><span class="glyphicon glyphicon-floppy-save"></span> Save Table</button>
                                </div>
                            </iata-rate-grid>
                            <airline-buying-rate-grid ng-model="model.airlineBuyingRateTable" on-change="updateModel(model)" rate-type="3" ng-show="rateTypeId==3">
                                <div class="form-group" style="text-align: center">
                                    <button class="button btn-primary" ng-click="saveTable()"><span class="glyphicon glyphicon-floppy-save"></span> Save Table</button>
                                </div>
                            </airline-buying-rate-grid>
                            <agent-buying-rate-grid ng-model="model.companyWrappers" on-change="updateModel(model)" rate-type="1" ng-show="rateTypeId==1">
                                <div class="form-group" style="text-align: center">
                                    <button class="button btn-primary" ng-click="saveTable()"><span class="glyphicon glyphicon-floppy-save"></span> Save Table</button>
                                </div>
                            </agent-buying-rate-grid>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <pager ng-model="totalRows" size="pageSize" on-change="getPage(skip);" reset="reset"></pager>
                    </td>
                </tr>

            </table>
        </div>
    </form>
</div>

elt_source/ELT.WEB-VS2013/ELT.WEB/Views/MasterData/ScheduleB.cshtml
@{
    ViewBag.Title = "ScheduleB";
    Layout = "~/Views/Shared/_LayoutOperation.cshtml";
}


<iframe id ="ContentFrame" scrolling="no"   frameborder="0" width="100%" onload="autoResize('ContentFrame');" src="@Url.Content("~/IFF_MAIN/ASPX/Misc/SBMaster.aspx")"></iframe>